version: '3'
services:
  kafka_node_1:
    image: "sscaling/jmx-prometheus-exporter:0.12.0"
    ports:
     - "5556:5556"
    environment:
     CONFIG_YML : "/etc/jmx_exporter/config.yml"
     JVM_OPTS: "-Xmx128M"
    volumes:
     - ./etc/jmx_exporter/config_kafka.yml:/etc/jmx_exporter/config.yml
    container_name: kafka_node_1
    networks:
      - kafka_net

networks:
  kafka_net:
    external: true