# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
 
rule_files:
  - alert.yml

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
# rule_files:
#   # - "first_rules.yml"
#   # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'kafka'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: [ '10.1.7.159:5556' ]
        labels:
          service: 'kafka_node_1'
    - targets: [ '10.1.7.191:5556' ]
        labels:
          service: 'kafka_node_2'
    - targets: [ '10.1.7.193:5556' ]
        labels:
          service: 'kafka_node_3' 